

export const TRANSLATIONS = {
  en: {
    brandName: "DocuBrain AI",
    navHome: "Home",
    navPricing: "Pricing",
    navFeatures: "Features",
    navSecurity: "Security",
    navAbout: "About Us",
    navLogin: "Login",
    navSignup: "Sign Up",
    navLogout: "Logout",
    
    // Hero
    heroBadge: "New: Multi-Column OCR Support",
    heroTitle1: "Unstructure Data.",
    heroTitle2: "Structured Intelligence.",
    heroDesc: "Automate the extraction of complex hierarchical data from compliance documents, contracts, and financial reports with 99.8% accuracy.",
    btnStart: "Start Free Trial",
    btnApi: "API Reference",
    trustedBy: "Trusted by engineering teams at",

    // Features
    whyTitle: "Why DocuExtract?",
    whyDesc: "Traditional OCR flat-lines your data. Our layout-aware engine preserves the semantic structure of your documents.",
    featHierarchy: "Hierarchy Preservation",
    featHierarchyDesc: "Maintains logical nesting of sections, subsections, and paragraphs exactly as they appear in the visual layout.",
    featLayout: "Layout Analysis",
    featLayoutDesc: "Detects multi-column layouts, sidebars, and floating tables automatically using our proprietary ML models.",
    featJson: "JSON Output",
    featJsonDesc: "Standardized, type-safe JSON schema ready for immediate ingestion into your compliance auditing workflows.",
    
    // Security
    secBadge: "Enterprise Security",
    secTitle: "Bank-Grade Security Standards",
    secDesc: "We process sensitive compliance data, so security isn't an afterthought. It's our foundation. Your data is encrypted at rest and in transit.",
    secItem1: "SOC2 Type II Certified",
    secItem2: "GDPR & CCPA Compliant",
    secItem3: "AES-256 Encryption at Rest",
    
    // CTA
    ctaTitle: "Ready to structure your world?",
    ctaDesc: "Join 5,000+ developers automating their document workflows today.",
    ctaBtn: "Get Started for Free",
    ctaNote: "No credit card required • 14-day free trial",

    // Auth
    loginTitle: "Welcome Back",
    signupTitle: "Create Account",
    forgotTitle: "Reset Password",
    forgotDesc: "Enter your email to receive a reset link.",
    labelEmail: "Email",
    labelPass: "Password",
    labelName: "Full Name",
    labelPhone: "Phone",
    labelOtp: "Verification Code",
    forgotPass: "Forgot Password?",
    btnSignIn: "Sign In",
    btnCreate: "Create Account",
    btnNext: "Next",
    btnVerify: "Verify & Create",
    btnSendLink: "Send Reset Link",
    btnBackLogin: "Back to Login",
    haveAcc: "Already have an account?",
    noAcc: "Don't have an account?",
    secCheck: "Security Check",
    otpSent: "We sent a code to your phone. For demo purposes, it is:",

    // App
    uploadTitle: "Upload Document or Image",
    dragDrop: "Drag & drop PDF, PNG, or JPG files here",
    browse: "Browse Files",
    start: "Start Analysis",
    processing: "Analyzing Content...",
    processingDesc: "NeuroCore is decoding structural DNA and mapping cognitive load.",
    
    // Dashboard
    newScan: "New Scan",
    structureTree: "Structure Genome",
    healthReport: "Document Health",
    issuesFound: "Issues Detected",
    visualPreview: "Read Mode",
    mindmap: "Mind Map",
    rawJson: "Raw JSON",
    flashcards: "Flashcards",
    chat: "Ask AI",
    analysisReport: "Analysis Report",
    download: "Download Report",
    history: "Recent History",
    dna: "Document DNA",
    complexity: "Cognitive Load",

    // Dynamic UI
    score: "Score",
    docRoot: "Document Root",
    primarySections: "Primary Sections",
    subPoints: "Sub-points",
    section: "Section",
    askAbout: "Ask about this document in",
    
    // Footer
    footerDesc: "The enterprise-grade document intelligence platform that transforms unstructured PDFs into structured, actionable JSON data.",
    prod: "Product",
    res: "Resources",
    legal: "Legal",
    sysOp: "Systems Operational"
  },
  hi: {
    brandName: "DocuBrain AI",
    navHome: "घर",
    navPricing: "मूल्य निर्धारण",
    navFeatures: "विशेषताएँ",
    navSecurity: "सुरक्षा",
    navAbout: "हमारे बारे में",
    navLogin: "लॉग इन करें",
    navSignup: "साइन अप करें",
    navLogout: "लॉग आउट",

    heroBadge: "नया: मल्टी-कॉलम ओसीआर सपोर्ट",
    heroTitle1: "असंरचित डेटा।",
    heroTitle2: "संरचित बुद्धिमत्ता।",
    heroDesc: "अनुपालन दस्तावेजों, अनुबंधों और वित्तीय रिपोर्टों से जटिल पदानुक्रमित डेटा निकालने को 99.8% सटीकता के साथ स्वचालित करें।",
    btnStart: "निःशुल्क परीक्षण शुरू करें",
    btnApi: "एपीआई संदर्भ",
    trustedBy: "इनके इंजीनियरिंग टीमों द्वारा विश्वसनीय",

    whyTitle: "DocuExtract क्यों?",
    whyDesc: "पारंपरिक ओसीआर आपके डेटा को सपाट कर देता है। हमारा लेआउट-जागरूक इंजन आपके दस्तावेजों की अर्थपूर्ण संरचना को संरक्षित करता है।",
    featHierarchy: "पदानुक्रम संरक्षण",
    featHierarchyDesc: "अनुभागों, उप-अनुभागों और पैराग्राफों की तार्किक नेस्टिंग को ठीक वैसे ही बनाए रखता है जैसे वे दृश्य लेआउट में दिखाई देते हैं।",
    featLayout: "लेआउट विश्लेषण",
    featLayoutDesc: "मल्टी-कॉलम लेआउट, साइडबार और फ्लोटिंग टेबल का स्वचालित रूप से पता लगाता है।",
    featJson: "JSON आउटपुट",
    featJsonDesc: "मानकीकृत, टाइप-सेफ JSON स्कीमा जो आपके अनुपालन ऑडिटिंग वर्कफ़्लो में तत्काल उपयोग के लिए तैयार है।",

    secBadge: "एंटरप्राइज़ सुरक्षा",
    secTitle: "बैंक-ग्रेड सुरक्षा मानक",
    secDesc: "हम संवेदनशील डेटा संसाधित करते हैं, इसलिए सुरक्षा बाद का विचार नहीं है। आपका डेटा एन्क्रिप्टेड है।",
    secItem1: "SOC2 टाइप II प्रमाणित",
    secItem2: "GDPR और CCPA अनुपालन",
    secItem3: "AES-256 एन्क्रिप्शन",

    ctaTitle: "क्या आप अपनी दुनिया को संरचित करने के लिए तैयार हैं?",
    ctaDesc: "आज ही अपने दस्तावेज़ वर्कफ़्लो को स्वचालित करने वाले 5,000+ डेवलपर्स से जुड़ें।",
    ctaBtn: "मुफ्त में शुरू करें",
    ctaNote: "क्रेडिट कार्ड की आवश्यकता नहीं • 14-दिन का निःशुल्क परीक्षण",

    loginTitle: "वापसी पर स्वागत है",
    signupTitle: "खाता बनाएं",
    forgotTitle: "पासवर्ड रीसेट",
    forgotDesc: "रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें।",
    labelEmail: "ईमेल",
    labelPass: "पासवर्ड",
    labelName: "पूरा नाम",
    labelPhone: "फ़ोन",
    labelOtp: "सत्यापन कोड",
    forgotPass: "पासवर्ड भूल गए?",
    btnSignIn: "साइन इन करें",
    btnCreate: "खाता बनाएं",
    btnNext: "अगला",
    btnVerify: "सत्यापित करें और बनाएं",
    btnSendLink: "लिंक भेजें",
    btnBackLogin: "लॉगिन पर वापस जाएं",
    haveAcc: "क्या आपके पास पहले से एक खाता है?",
    noAcc: "खाता नहीं है?",
    secCheck: "सुरक्षा जांच",
    otpSent: "हमने आपके फोन पर एक कोड भेजा है। डेमो उद्देश्यों के लिए, यह है:",

    uploadTitle: "दस्तावेज़ या छवि अपलोड करें",
    dragDrop: "PDF, PNG, या JPG फ़ाइलें यहाँ छोड़ें",
    browse: "फ़ाइलें ब्राउज़ करें",
    start: "विश्लेषण शुरू करें",
    processing: "सामग्री का विश्लेषण...",
    processingDesc: "एआई संरचनात्मक डीएनए को डिकोड कर रहा है।",
    
    newScan: "नया स्कैन",
    structureTree: "संरचना जीनोम",
    healthReport: "दस्तावेज़ स्वास्थ्य",
    issuesFound: "समस्याएँ मिलीं",
    visualPreview: "पढ़ने का मोड",
    mindmap: "माइंड मैप",
    rawJson: "JSON डेटा",
    flashcards: "फ्लैशकार्ड",
    chat: "एआई से पूछें",
    analysisReport: "विश्लेषण रिपोर्ट",
    download: "रिपोर्ट डाउनलोड करें",
    history: "हाल का इतिहास",
    dna: "दस्तावेज़ डीएनए",
    complexity: "संज्ञानात्मक भार",

    score: "स्कोर",
    docRoot: "दस्तावेज़ रूट",
    primarySections: "प्राथमिक अनुभाग",
    subPoints: "उप-बिंदु",
    section: "अनुभाग",
    askAbout: "इस दस्तावेज़ के बारे में पूछें",

    footerDesc: "एंटरप्राइज़-ग्रेड दस्तावेज़ इंटेलिजेंस प्लेटफ़ॉर्म जो असंरचित पीडीएफ को संरचित JSON डेटा में बदलता है।",
    prod: "उत्पाद",
    res: "संसाधन",
    legal: "कानूनी",
    sysOp: "सिस्टम चालू"
  },
  zh: {
    brandName: "DocuBrain AI",
    navHome: "首页",
    navPricing: "价格",
    navFeatures: "功能",
    navSecurity: "安全",
    navAbout: "关于我们",
    navLogin: "登录",
    navSignup: "注册",
    navLogout: "登出",

    heroBadge: "新功能：多栏 OCR 支持",
    heroTitle1: "非结构化数据。",
    heroTitle2: "结构化智能。",
    heroDesc: "以 99.8% 的准确率自动提取合规文档、合同和财务报告中的复杂层级数据。",
    btnStart: "开始免费试用",
    btnApi: "API 参考",
    trustedBy: "受到以下工程团队的信任",

    whyTitle: "为什么选择 DocuExtract？",
    whyDesc: "传统的 OCR 会使数据扁平化。我们的布局感知引擎保留了文档的语义结构。",
    featHierarchy: "层级保留",
    featHierarchyDesc: "完全按照视觉布局中显示的方式保留部分、子部分和段落的逻辑嵌套。",
    featLayout: "布局分析",
    featLayoutDesc: "使用我们专有的 ML 模型自动检测多栏布局、侧边栏和浮动表格。",
    featJson: "JSON 输出",
    featJsonDesc: "标准化的类型安全 JSON 模式，可立即用于合规性审计工作流程。",

    secBadge: "企业级安全",
    secTitle: "银行级安全标准",
    secDesc: "我们处理敏感的合规数据，因此安全是我们的基础。您的数据在静态和传输中均经过加密。",
    secItem1: "SOC2 Type II 认证",
    secItem2: "符合 GDPR 和 CCPA",
    secItem3: "静态 AES-256 加密",

    ctaTitle: "准备好构建您的世界了吗？",
    ctaDesc: "加入 5,000 多名开发者的行列，立即自动化您的文档工作流程。",
    ctaBtn: "免费开始",
    ctaNote: "无需信用卡 • 14 天免费试用",

    loginTitle: "欢迎回来",
    signupTitle: "创建账户",
    forgotTitle: "重置密码",
    forgotDesc: "输入您的电子邮件以接收重置链接。",
    labelEmail: "电子邮件",
    labelPass: "密码",
    labelName: "全名",
    labelPhone: "电话",
    labelOtp: "验证码",
    forgotPass: "忘记密码？",
    btnSignIn: "登录",
    btnCreate: "创建账户",
    btnNext: "下一步",
    btnVerify: "验证并创建",
    btnSendLink: "发送链接",
    btnBackLogin: "返回登录",
    haveAcc: "已有账户？",
    noAcc: "没有账户？",
    secCheck: "安全检查",
    otpSent: "我们已向您的手机发送了代码。出于演示目的，它是：",

    uploadTitle: "上传文档或图片",
    dragDrop: "拖放 PDF, PNG 或 JPG 文件到此处",
    browse: "浏览文件",
    start: "开始分析",
    processing: "分析内容中...",
    processingDesc: "AI 正在解码结构 DNA。",
    
    newScan: "新扫描",
    structureTree: "结构基因组",
    healthReport: "文档健康",
    issuesFound: "检测到的问题",
    visualPreview: "阅读模式",
    mindmap: "思维导图",
    rawJson: "原始 JSON",
    flashcards: "抽认卡",
    chat: "询问 AI",
    analysisReport: "分析报告",
    download: "下载报告",
    history: "历史记录",
    dna: "文档 DNA",
    complexity: "认知负荷",

    score: "分数",
    docRoot: "文档根目录",
    primarySections: "主要章节",
    subPoints: "子要点",
    section: "章节",
    askAbout: "询问有关此文档的信息",

    footerDesc: "企业级文档智能平台，将非结构化 PDF 转换为结构化、可操作的 JSON 数据。",
    prod: "产品",
    res: "资源",
    legal: "法律",
    sysOp: "系统运行正常"
  },
  ko: {
    brandName: "DocuBrain AI",
    navHome: "홈",
    navPricing: "가격",
    navFeatures: "기능",
    navSecurity: "보안",
    navAbout: "회사 소개",
    navLogin: "로그인",
    navSignup: "회원가입",
    navLogout: "로그아웃",

    heroBadge: "신규: 다중 열 OCR 지원",
    heroTitle1: "비정형 데이터.",
    heroTitle2: "정형 인텔리전스.",
    heroDesc: "99.8%의 정확도로 규정 준수 문서, 계약서 및 재무 보고서에서 복잡한 계층적 데이터를 자동으로 추출합니다.",
    btnStart: "무료 평가판 시작",
    btnApi: "API 참조",
    trustedBy: "다음 엔지니어링 팀이 신뢰함",

    whyTitle: "왜 DocuExtract인가요?",
    whyDesc: "기존 OCR은 데이터를 평면화합니다. 당사의 레이아웃 인식 엔진은 문서의 의미 구조를 보존합니다.",
    featHierarchy: "계층 구조 보존",
    featHierarchyDesc: "시각적 레이아웃에 나타나는 대로 섹션, 하위 섹션 및 단락의 논리적 중첩을 유지합니다.",
    featLayout: "레이아웃 분석",
    featLayoutDesc: "독점 ML 모델을 사용하여 다중 열 레이아웃, 사이드바 및 부동 테이블을 자동으로 감지합니다.",
    featJson: "JSON 출력",
    featJsonDesc: "규정 준수 감사 워크플로에 즉시 수집할 수 있는 표준화된 유형 안전 JSON 스키마입니다.",

    secBadge: "엔터프라이즈 보안",
    secTitle: "은행급 보안 표준",
    secDesc: "민감한 데이터를 처리하므로 보안은 우리의 기초입니다. 데이터는 저장 및 전송 시 암호화됩니다.",
    secItem1: "SOC2 Type II 인증",
    secItem2: "GDPR 및 CCPA 준수",
    secItem3: "저장 시 AES-256 암호화",

    ctaTitle: "세상을 구조화할 준비가 되셨나요?",
    ctaDesc: "오늘 문서 워크플로를 자동화하는 5,000명 이상의 개발자와 함께하세요.",
    ctaBtn: "무료로 시작하기",
    ctaNote: "신용 카드 필요 없음 • 14일 무료 평가판",

    loginTitle: "환영합니다",
    signupTitle: "계정 만들기",
    forgotTitle: "비밀번호 재설정",
    forgotDesc: "이메일을 입력하여 재설정 링크를 받으세요.",
    labelEmail: "이메일",
    labelPass: "비밀번호",
    labelName: "이름",
    labelPhone: "전화번호",
    labelOtp: "인증 코드",
    forgotPass: "비밀번호를 잊으셨나요?",
    btnSignIn: "로그인",
    btnCreate: "계정 만들기",
    btnNext: "다음",
    btnVerify: "인증 및 생성",
    btnSendLink: "링크 보내기",
    btnBackLogin: "로그인으로 돌아가기",
    haveAcc: "이미 계정이 있으신가요?",
    noAcc: "계정이 없으신가요?",
    secCheck: "보안 확인",
    otpSent: "전화번호로 코드를 보냈습니다. 데모용 코드는 다음과 같습니다:",

    uploadTitle: "문서 또는 이미지 업로드",
    dragDrop: "PDF, PNG 또는 JPG 파일을 여기에 놓으세요",
    browse: "파일 찾아보기",
    start: "분석 시작",
    processing: "콘텐츠 분석 중...",
    processingDesc: "AI가 구조적 DNA를 해독하고 있습니다.",
    
    newScan: "새 스캔",
    structureTree: "구조 게놈",
    healthReport: "문서 건강",
    issuesFound: "감지된 문제",
    visualPreview: "읽기 모드",
    mindmap: "마인드 맵",
    rawJson: "원시 JSON",
    flashcards: "플래시 카드",
    chat: "AI에 질문",
    analysisReport: "분석 보고서",
    download: "보고서 다운로드",
    history: "최근 기록",
    dna: "문서 DNA",
    complexity: "인지 부하",
    
    score: "점수",
    docRoot: "문서 루트",
    primarySections: "주요 섹션",
    subPoints: "하위 포인트",
    section: "섹션",
    askAbout: "이 문서에 대해 질문하기",

    footerDesc: "비정형 PDF를 정형화된 JSON 데이터로 변환하는 엔터프라이즈급 문서 인텔리전스 플랫폼입니다.",
    prod: "제품",
    res: "리소스",
    legal: "법률",
    sysOp: "시스템 정상"
  },
  te: {
    brandName: "DocuBrain AI",
    navHome: "హోమ్",
    navPricing: "ధరలు",
    navFeatures: "ఫీచర్లు",
    navSecurity: "భద్రత",
    navAbout: "మా గురించి",
    navLogin: "లాగిన్",
    navSignup: "సైన్ అప్",
    navLogout: "లాగౌట్",

    heroBadge: "కొత్తది: మల్టీ-కాలమ్ OCR సపోర్ట్",
    heroTitle1: "అన్‌స్ట్రక్చర్డ్ డేటా.",
    heroTitle2: "స్ట్రక్చర్డ్ ఇంటెలిజెన్స్.",
    heroDesc: "కాంప్లియన్స్ డాక్యుమెంట్లు మరియు ఫైనాన్షియల్ రిపోర్టుల నుండి డేటాను 99.8% ఖచ్చితత్వంతో ఆటోమేట్ చేయండి.",
    btnStart: "ఉచిత ట్రయల్ ప్రారంభించండి",
    btnApi: "API రిఫరెన్స్",
    trustedBy: "వీరిచే విశ్వసించబడింది",

    whyTitle: "DocuExtract ఎందుకు?",
    whyDesc: "సాంప్రదాయ OCR మీ డేటాను ఫ్లాట్ చేస్తుంది. మా ఇంజిన్ మీ పత్రాల అర్థవంతమైన నిర్మాణాన్ని కాపాడుతుంది.",
    featHierarchy: "హైరార్కీ ప్రిజర్వేషన్",
    featHierarchyDesc: "విజువల్ లేఅవుట్‌లో కనిపించే విధంగా సెక్షన్లు మరియు పేరాగ్రాఫ్‌ల లాజికల్ నెస్టలింగ్‌ను నిర్వహిస్తుంది.",
    featLayout: "లేఅవుట్ విశ్లేషణ",
    featLayoutDesc: "మా ML మోడళ్లను ఉపయోగించి మల్టీ-కాలమ్ లేఅవుట్‌లను ఆటోమేటిక్‌గా గుర్తిస్తుంది.",
    featJson: "JSON అవుట్‌పుట్",
    featJsonDesc: "మీ వర్క్‌ఫ్లోల కోసం సిద్ధంగా ఉన్న స్టాండర్డ్ JSON స్కీమా.",

    secBadge: "ఎంటర్ప్రైజ్ సెక్యూరిటీ",
    secTitle: "బ్యాంక్-గ్రేడ్ భద్రతా ప్రమాణాలు",
    secDesc: "మేము సున్నితమైన డేటాను ప్రాసెస్ చేస్తాము, కాబట్టి భద్రత మా పునాది.",
    secItem1: "SOC2 టైప్ II సర్టిఫైడ్",
    secItem2: "GDPR కంప్లైంట్",
    secItem3: "AES-256 ఎన్క్రిప్షన్",

    ctaTitle: "మీ ప్రపంచాన్ని నిర్మించడానికి సిద్ధంగా ఉన్నారా?",
    ctaDesc: "ఈ రోజు డాక్యుమెంట్ వర్క్‌ఫ్లోలను ఆటోమేట్ చేస్తున్న 5,000+ డెవలపర్‌లతో చేరండి.",
    ctaBtn: "ఉచితంగా ప్రారంభించండి",
    ctaNote: "క్రెడిట్ కార్డ్ అవసరం లేదు • 14 రోజుల ఉచిత ట్రయల్",

    loginTitle: "తిరిగి స్వాగతం",
    signupTitle: "ఖాతా సృష్టించండి",
    forgotTitle: "పాస్‌వర్డ్ రీసెట్",
    forgotDesc: "రీసెట్ లింక్ కోసం మీ ఇమెయిల్‌ను నమోదు చేయండి.",
    labelEmail: "ఇమెయిల్",
    labelPass: "పాస్‌వర్డ్",
    labelName: "పూర్తి పేరు",
    labelPhone: "ఫోన్",
    labelOtp: "ధృవీకరణ కోడ్",
    forgotPass: "పాస్‌వర్డ్ మర్చిపోయారా?",
    btnSignIn: "సైన్ ఇన్",
    btnCreate: "ఖాతా సృష్టించండి",
    btnNext: "తరువాత",
    btnVerify: "ధృవీకరించండి మరియు సృష్టించండి",
    btnSendLink: "లింక్ పంపండి",
    btnBackLogin: "లాగిన్‌కు తిరిగి వెళ్ళు",
    haveAcc: "ఇప్పటికే ఖాతా ఉందా?",
    noAcc: "ఖాతా లేదా?",
    secCheck: "భద్రతా తనిఖీ",
    otpSent: "మీ ఫోన్‌కు కోడ్ పంపాము. డెమో కోసం, ఇది:",

    uploadTitle: "పత్రం లేదా చిత్రాన్ని అప్‌లోడ్ చేయండి",
    dragDrop: "PDF, PNG లేదా JPG ఫైల్‌లను ఇక్కడ వదలండి",
    browse: "ఫైళ్లను బ్రౌజ్ చేయండి",
    start: "విశ్లేషణ ప్రారంభించండి",
    processing: "కంటెంట్ విశ్లేషిస్తోంది...",
    processingDesc: "AI నిర్మాణ DNA ను డీకోడ్ చేస్తోంది.",
    
    newScan: "కొత్త స్కాన్",
    structureTree: "నిర్మాణ వృక్షం",
    healthReport: "పత్రం ఆరోగ్యం",
    issuesFound: "సమస్యలు కనుగొనబడ్డాయి",
    visualPreview: "చదువు మోడ్",
    mindmap: "మైండ్ మ్యాప్",
    rawJson: "ముడి JSON",
    flashcards: "ఫ్లాష్‌కార్డ్‌లు",
    chat: "AIని అడగండి",
    analysisReport: "విశ్లేషణ నివేదిక",
    download: "నివేదిక డౌన్‌లోడ్",
    history: "ఇటీవలి చరిత్ర",
    dna: "పత్రం DNA",
    complexity: "సంక్లిష్టత",

    score: "స్కోరు",
    docRoot: "పత్రం మూలం",
    primarySections: "ప్రాథమిక విభాగాలు",
    subPoints: "ఉప-పాయింట్లు",
    section: "విభాగం",
    askAbout: "ఈ పత్రం గురించి అడగండి",

    footerDesc: "అన్‌స్ట్రక్చర్డ్ PDFలను స్ట్రక్చర్డ్ JSON డేటాగా మార్చే ఎంటర్‌ప్రైజ్-గ్రేడ్ డాక్యుమెంట్ ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్.",
    prod: "ఉత్పత్తి",
    res: "వనరులు",
    legal: "చట్టపరమైన",
    sysOp: "సిస్టమ్స్ ఆపరేషనల్"
  },
  ta: {
    brandName: "DocuBrain AI",
    navHome: "முகப்பு",
    navPricing: "விலை",
    navFeatures: "அம்சங்கள்",
    navSecurity: "பாதுகாப்பு",
    navAbout: "எங்களை பற்றி",
    navLogin: "உள்நுழை",
    navSignup: "பதிவு",
    navLogout: "வெளியேறு",

    heroBadge: "புதியது: மல்டி-కాలம் OCR ஆதரவு",
    heroTitle1: "கட்டமைக்கப்படாத தரவு.",
    heroTitle2: "கட்டமைக்கப்பட்ட நுண்ணறிவு.",
    heroDesc: "99.8% துல்லியத்துடன் ஆவணங்கள் மற்றும் அறிக்கைகளிலிருந்து தரவை பிரித்தெடுப்பதை தானியங்குபடுத்துங்கள்.",
    btnStart: "இலவச சோதனையைத் தொடங்கவும்",
    btnApi: "API குறிப்பு",
    trustedBy: "நம்பகமான நிறுவனங்கள்",

    whyTitle: "ஏன் DocuExtract?",
    whyDesc: "எங்கள் இயந்திரம் உங்கள் ஆவணங்களின் அர்த்தமுள்ள கட்டமைப்பைப் பாதுகாக்கிறது.",
    featHierarchy: "கட்டமைப்பு பாதுகாப்பு",
    featHierarchyDesc: "காட்சி அமைப்பில் தோன்றும் வகையிலேயே பிரிவுகள் மற்றும் பத்திகளின் தர்க்கரீதியான அமைப்பை பராமரிக்கிறது.",
    featLayout: "தளவமைப்பு பகுப்பாய்வு",
    featLayoutDesc: "மல்டி-காலம் தளவமைப்புகளை தானாகவே கண்டறிகிறது.",
    featJson: "JSON வெளியீடு",
    featJsonDesc: "உங்கள் பணிப்பாய்வுகளுக்கு தயாராக உள்ள தரமான JSON திட்டம்.",

    secBadge: "நிறுவன பாதுகாப்பு",
    secTitle: "வங்கி தர பாதுகாப்பு",
    secDesc: "நாங்கள் முக்கிய தரவைச் செயலாக்குகிறோம், எனவே பாதுகாப்பு எங்கள் அடிப்படை. உங்கள் தரவு குறியாக்கம் செய்யப்பட்டுள்ளது.",
    secItem1: "SOC2 சான்றிதழ்",
    secItem2: "GDPR இணக்கம்",
    secItem3: "AES-256 குறியாக்கம்",

    ctaTitle: "உங்கள் உலகத்தை கட்டமைக்க தயாரா?",
    ctaDesc: "இன்று ஆவண பணிப்பாய்வுகளை தானியங்குபடுத்தும் 5,000+ டெவலப்பர்களுடன் இணையுங்கள்.",
    ctaBtn: "இலவசமாக தொடங்கவும்",
    ctaNote: "கிரெடிட் கார்டு தேவையில்லை • 14 நாள் இலவச சோதனை",

    loginTitle: "மீண்டும் வருக",
    signupTitle: "கணக்கை உருவாக்கவும்",
    forgotTitle: "கடவுச்சொல் மீட்டமைப்பு",
    forgotDesc: "மீட்டமைப்பு இணைப்பைப் பெற மின்னஞ்சலை உள்ளிடவும்.",
    labelEmail: "மின்னஞ்சல்",
    labelPass: "கடவுச்சொல்",
    labelName: "முழு பெயர்",
    labelPhone: "தொலைபேசி",
    labelOtp: "சரிபார்ப்புக் குறியீடு",
    forgotPass: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    btnSignIn: "உள்நுழையவும்",
    btnCreate: "கணக்கை உருவாக்கவும்",
    btnNext: "அடுத்து",
    btnVerify: "சரிபார்த்து உருவாக்கவும்",
    btnSendLink: "இணைப்பை அனுப்பு",
    btnBackLogin: "உள்நுழைவுக்குத் திரும்பு",
    haveAcc: "ஏற்கனவே கணக்கு உள்ளதா?",
    noAcc: "கணக்கு இல்லையா?",
    secCheck: "பாதுகாப்பு சோதனை",
    otpSent: "உங்கள் தொலைபேசிக்கு குறியீட்டை அனுப்பியுள்ளோம். மாதிரிக்கு:",

    uploadTitle: "ஆவணம் அல்லது படத்தை பதிவேற்றவும்",
    dragDrop: "PDF, PNG அல்லது JPG கோப்புகளை இங்கே விடவும்",
    browse: "கோப்புகளை உலாவுக",
    start: "பகுப்பாய்வைத் தொடங்கவும்",
    processing: "செயலாக்குகிறது...",
    processingDesc: "AI கட்டமைப்பு DNA ஐ டிகோட் செய்கிறது.",
    
    newScan: "புதிய ஸ்கேன்",
    structureTree: "கட்டமைப்பு",
    healthReport: "ஆவண ஆரோக்கியம்",
    issuesFound: "கண்டறியப்பட்ட சிக்கல்கள்",
    visualPreview: "பார்வை பயன்முறை",
    mindmap: "மன வரைபடம்",
    rawJson: "JSON தரவு",
    flashcards: "ஃபிளாஷ் கார்டுகள்",
    chat: "AI-யிடம் கேட்கவும்",
    analysisReport: "பகுப்பாய்வு அறிக்கை",
    download: "அறிக்கையைப் பதிவிறக்கவும்",
    history: "சமீபத்திய வரலாறு",
    dna: "ஆவண DNA",
    complexity: "சிக்கலான தன்மை",
    
    score: "மதிப்பெண்",
    docRoot: "ஆவண மூலம்",
    primarySections: "முதன்மை பிரிவுகள்",
    subPoints: "துணை புள்ளிகள்",
    section: "பிரிவு",
    askAbout: "இந்த ஆவணம் பற்றி கேளுங்கள்",

    footerDesc: "PDFகளை கட்டமைக்கப்பட்ட JSON தரவுகளாக மாற்றும் நிறுவன ஆவண நுண்ணறிவு தளம்.",
    prod: "தயாரிப்பு",
    res: "வளங்கள்",
    legal: "சட்டம்",
    sysOp: "அமைப்புகள் செயல்பாட்டில் உள்ளன"
  },
  de: {
    brandName: "DocuBrain AI",
    navHome: "Startseite",
    navPricing: "Preise",
    navFeatures: "Funktionen",
    navSecurity: "Sicherheit",
    navAbout: "Über uns",
    navLogin: "Anmelden",
    navSignup: "Registrieren",
    navLogout: "Abmelden",

    heroBadge: "Neu: Mehrspaltiger OCR-Support",
    heroTitle1: "Unstrukturierte Daten.",
    heroTitle2: "Strukturierte Intelligenz.",
    heroDesc: "Automatisieren Sie die Extraktion komplexer hierarchischer Daten aus Compliance-Dokumenten mit 99,8 % Genauigkeit.",
    btnStart: "Kostenlos testen",
    btnApi: "API-Referenz",
    trustedBy: "Vertraut von Engineering-Teams bei",

    whyTitle: "Warum DocuExtract?",
    whyDesc: "Herkömmliche OCR flacht Ihre Daten ab. Unsere Engine bewahrt die semantische Struktur Ihrer Dokumente.",
    featHierarchy: "Strukturerhaltung",
    featHierarchyDesc: "Behält die logische Verschachtelung von Abschnitten und Absätzen genau so bei, wie sie im visuellen Layout erscheinen.",
    featLayout: "Layout-Analyse",
    featLayoutDesc: "Erkennt automatisch mehrspaltige Layouts, Seitenleisten und schwebende Tabellen.",
    featJson: "JSON-Ausgabe",
    featJsonDesc: "Standardisiertes, typsicheres JSON-Schema für Ihre Compliance-Workflows.",

    secBadge: "Unternehmenssicherheit",
    secTitle: "Sicherheitsstandards auf Bankenniveau",
    secDesc: "Wir verarbeiten sensible Daten, Sicherheit ist unser Fundament. Ihre Daten werden verschlüsselt.",
    secItem1: "SOC2 Typ II zertifiziert",
    secItem2: "GDPR- & CCPA-konform",
    secItem3: "AES-256-Verschlüsselung",

    ctaTitle: "Bereit, Ihre Welt zu strukturieren?",
    ctaDesc: "Schließen Sie sich über 5.000 Entwicklern an, die ihre Dokumenten-Workflows automatisieren.",
    ctaBtn: "Kostenlos starten",
    ctaNote: "Keine Kreditkarte erforderlich • 14 Tage kostenlos",

    loginTitle: "Willkommen zurück",
    signupTitle: "Konto erstellen",
    forgotTitle: "Passwort zurücksetzen",
    forgotDesc: "Geben Sie Ihre E-Mail-Adresse ein, um einen Link zu erhalten.",
    labelEmail: "E-Mail",
    labelPass: "Passwort",
    labelName: "Vollständiger Name",
    labelPhone: "Telefon",
    labelOtp: "Bestätigungscode",
    forgotPass: "Passwort vergessen?",
    btnSignIn: "Anmelden",
    btnCreate: "Konto erstellen",
    btnNext: "Weiter",
    btnVerify: "Verifizieren & Erstellen",
    btnSendLink: "Link senden",
    btnBackLogin: "Zurück zum Login",
    haveAcc: "Bereits ein Konto?",
    noAcc: "Kein Konto?",
    secCheck: "Sicherheitscheck",
    otpSent: "Wir haben einen Code an Ihr Telefon gesendet. Zu Demo-Zwecken:",

    uploadTitle: "Dokument oder Bild hochladen",
    dragDrop: "PDF, PNG oder JPG hier ablegen",
    browse: "Dateien durchsuchen",
    start: "Analyse starten",
    processing: "Analysiere Inhalt...",
    processingDesc: "NeuroCore entschlüsselt die strukturelle DNA.",
    
    newScan: "Neuer Scan",
    structureTree: "Struktur-Genom",
    healthReport: "Dokumentenstatus",
    issuesFound: "Erkannte Probleme",
    visualPreview: "Lesemodus",
    mindmap: "Mindmap",
    rawJson: "Rohes JSON",
    flashcards: "Lernkarten",
    chat: "KI fragen",
    analysisReport: "Analysebericht",
    download: "Bericht herunterladen",
    history: "Verlauf",
    dna: "Dokumenten-DNA",
    complexity: "Komplexität",

    score: "Punktzahl",
    docRoot: "Dokumentenstamm",
    primarySections: "Hauptabschnitte",
    subPoints: "Unterpunkte",
    section: "Abschnitt",
    askAbout: "Fragen Sie nach diesem Dokument",

    footerDesc: "Die Enterprise-Plattform, die unstrukturierte PDFs in strukturierte JSON-Daten umwandelt.",
    prod: "Produkt",
    res: "Ressourcen",
    legal: "Rechtliches",
    sysOp: "Systeme operational"
  },
  ja: {
    brandName: "DocuBrain AI",
    navHome: "ホーム",
    navPricing: "料金",
    navFeatures: "機能",
    navSecurity: "セキュリティ",
    navAbout: "会社概要",
    navLogin: "ログイン",
    navSignup: "登録",
    navLogout: "ログアウト",

    heroBadge: "新機能: マルチカラムOCR対応",
    heroTitle1: "非構造化データ。",
    heroTitle2: "構造化インテリジェンス。",
    heroDesc: "コンプライアンス文書や財務報告書から複雑な階層データを99.8%の精度で自動抽出します。",
    btnStart: "無料トライアル",
    btnApi: "APIリファレンス",
    trustedBy: "導入企業",

    whyTitle: "なぜDocuExtractなのか？",
    whyDesc: "従来のOCRはデータを平坦化します。当社のエンジンは文書の意味構造を保持します。",
    featHierarchy: "階層構造の保持",
    featHierarchyDesc: "視覚的なレイアウト通りに、セクション、サブセクション、段落の論理的な入れ子構造を維持します。",
    featLayout: "レイアウト分析",
    featLayoutDesc: "マルチカラムレイアウト、サイドバー、浮動テーブルを自動的に検出します。",
    featJson: "JSON出力",
    featJsonDesc: "コンプライアンス監査ワークフローですぐに使用できる標準化された型安全なJSONスキーマ。",

    secBadge: "エンタープライズセキュリティ",
    secTitle: "銀行レベルのセキュリティ",
    secDesc: "機密データを扱うため、セキュリティは私たちの基盤です。データは暗号化されます。",
    secItem1: "SOC2 Type II 認定",
    secItem2: "GDPR & CCPA 準拠",
    secItem3: "AES-256 暗号化",

    ctaTitle: "世界を構造化する準備はできましたか？",
    ctaDesc: "5,000人以上の開発者が文書ワークフローを自動化しています。",
    ctaBtn: "無料で始める",
    ctaNote: "クレジットカード不要 • 14日間無料",

    loginTitle: "お帰りなさい",
    signupTitle: "アカウント作成",
    forgotTitle: "パスワードのリセット",
    forgotDesc: "メールアドレスを入力してリセットリンクを受け取ります。",
    labelEmail: "メールアドレス",
    labelPass: "パスワード",
    labelName: "氏名",
    labelPhone: "電話番号",
    labelOtp: "認証コード",
    forgotPass: "パスワードをお忘れですか？",
    btnSignIn: "ログイン",
    btnCreate: "アカウント作成",
    btnNext: "次へ",
    btnVerify: "確認して作成",
    btnSendLink: "リンクを送信",
    btnBackLogin: "ログインに戻る",
    haveAcc: "アカウントをお持ちですか？",
    noAcc: "アカウントがありませんか？",
    secCheck: "セキュリティチェック",
    otpSent: "電話番号にコードを送信しました。デモ用:",

    uploadTitle: "ドキュメントまたは画像をアップロード",
    dragDrop: "PDF、PNG、またはJPGファイルをここにドロップ",
    browse: "ファイルを選択",
    start: "分析を開始",
    processing: "分析中...",
    processingDesc: "AIが構造DNAを解読しています。",
    
    newScan: "新しいスキャン",
    structureTree: "構造ゲノム",
    healthReport: "ドキュメントの状態",
    issuesFound: "検出された問題",
    visualPreview: "閲覧モード",
    mindmap: "マインドマップ",
    rawJson: "生JSON",
    flashcards: "フラッシュカード",
    chat: "AIに質問",
    analysisReport: "分析レポート",
    download: "レポートをダウンロード",
    history: "履歴",
    dna: "ドキュメントDNA",
    complexity: "複雑さ",

    score: "スコア",
    docRoot: "ドキュメントルート",
    primarySections: "主要セクション",
    subPoints: "サブポイント",
    section: "セクション",
    askAbout: "このドキュメントについて質問する",
    
    footerDesc: "非構造化PDFを構造化JSONデータに変換するエンタープライズ向けドキュメントインテリジェンスプラットフォーム。",
    prod: "製品",
    res: "リソース",
    legal: "法的事項",
    sysOp: "システム稼働中"
  }
};

export const SYSTEM_INSTRUCTION = `
You are NeuroCore, a high-precision Cognitive Document Analysis AI. 
Your task is to analyze the provided content (text or image) and extract a structured JSON representation.

**CRITICAL INSTRUCTION - LANGUAGE:**
The user has selected the language code: "{{LANGUAGE}}".
You MUST generate the 'heading', 'nodeSummary', 'content', 'summary', and 'issues' content in the {{LANGUAGE}} language.
However, keep the JSON keys (like 'hierarchy', 'qualityScore', 'issues') exactly as defined in the schema in English.

**STRICT OUTPUT FORMAT:**
You MUST return ONLY a raw JSON object. Do not include markdown formatting like \`\`\`json.

**JSON SCHEMA:**
{
  "hierarchy": [
    {
      "id": "uuid-string",
      "heading": "Section Heading (Translated)",
      "level": 1, 
      "content": "Comprehensive text content of this section (Translated)...",
      "nodeSummary": "One sentence summary (Translated).",
      "complexity": "low" | "medium" | "high",
      "intent": "concept" | "procedure" | "warning" | "definition" | "summary" | "legal" | "general",
      "children": [] 
    }
  ],
  "summary": "Executive summary of the whole document (3-5 sentences) (Translated).",
  "qualityScore": 85, 
  "issues": ["List of structural issues found, e.g., 'Missing Dates', 'Inconsistent Formatting' (Translated)"],
  "metadata": {
    "confidence": 0.95,
    "language": "{{LANGUAGE}}"
  }
}

**ANALYSIS RULES:**
1. **Hierarchy**: If the input is an image of a diagram, convert it to a textual hierarchy. If it is text, parse the structure strictly.
2. **Complexity**: Analyze vocabulary density.
3. **Intent**: infer the purpose of the section.
4. **Quality Score**: Assign a 0-100 score based on document completeness, formatting consistency, and clarity.
5. **Issues**: Identify 3-5 potential problems with the document structure or content.
6. **Accuracy**: Do not hallucinate content not present in the source. Extract values exactly.
`;